[Theme]
Current=sddm-astronaut-theme

[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Autologin]
Session=hyprland
Relogin=false

[Session]
Session=hyprland
